Repository FRONTENDSCHOOL10/sibi11jo, pull requests merged in 2024-07, with the labels that each got.

#9 🎨 feat: iconfonts 추가
  index.html
  src/assets/fonts/icomoon.eot
  src/assets/fonts/icomoon.svg
  src/assets/fonts/icomoon.ttf
  src/assets/fonts/icomoon.woff
  src/assets/icons/icon-blog.png
  src/assets/icons/icon-checkbox-checked.svg
  src/assets/icons/icon-checkbox-default.svg
  src/assets/icons/icon-facebook.png
  src/assets/icons/icon-go-to-top.png
  src/assets/icons/icon-instagram.png
  src/assets/icons/icon-naver-post.png
  src/assets/icons/icon-radio-checked.svg
  src/assets/icons/icon-radio-default.svg
  src/assets/icons/icon-youtube.png
  src/styles/abstracts/_variables.scss
  src/styles/base/_iconfonts.scss
  src/styles/style.scss
Labels: enhancement

#13 💙 Component : 컴포넌트 추가 및 개선
  src/assets/fonts/icomoon.eot
  src/assets/fonts/icomoon.svg
  src/assets/fonts/icomoon.ttf
  src/assets/fonts/icomoon.woff
  src/components/template.html
  src/styles/abstracts/_variables.scss
  src/styles/base/_common.scss
  src/styles/base/_iconfonts.scss
  src/styles/base/_reset.scss
  src/styles/components/_button.scss
  src/styles/components/_checkbox.scss
  src/styles/components/_radioButton.scss
  src/styles/components/_textInput.scss
  src/styles/foundations/_colors.scss
Labels: 💙 Component

#18 ⚙️ Ci : pocketbase 기초 설정
  .env
  package-lock.json
  package.json
  src/api/pocketbase.js
  src/layout/footer.html
Labels: 🎨 Feat, ⚙️ Ci, 🎉 Init

#24 🎨 Feat : Footer 웹 컴포넌트 추가 및 기타 수정
  .github/PULL_REQUEST_TEMPLATE.md
  index.html
  main.js
  package-lock.json
  package.json
  src/assets/icons/logo_isms.png
  src/assets/icons/logo_privacy.png
  src/assets/icons/logo_tosspayments.png
  src/assets/icons/logo_wooriBank.png
  src/components/template.html
  src/layout/footer.html
  src/layout/footer.js
  src/styles/base/_common.scss
  src/styles/components/_button.scss
  src/styles/layout/_footer.scss
  vite.config.js
Labels: 💚 Docs, ✅ Test, 🎨 Feat, ⚙️ Ci, 🧡 Markup, 💙 Component

#25 💙 Component : 컴포넌트 수정(마크업 및 파일이름 변경)
  src/components/template.html
  src/styles/components/_productDetails.scss
  src/styles/components/_productInquiry.scss
  src/styles/components/_productReview.scss
  src/styles/components/_productTab.scss
  src/styles/components/_sectionHeader.scss
Labels: 💙 Component

#27 🧡 Markup : 로그인, 회원가입 페이지 추가
  src/pages/login.html
  src/pages/register.html
  src/styles/pages/_login.scss
  src/styles/pages/_register.scss
Labels: 🎨 Feat, 🧡 Markup

#34 ✅ Test : header, footer 영역 테스트
  index.html
  main.js
  public/favicon.svg
  public/logo.svg
  src/layout/footer/footer.html
  src/layout/footer/footer.js
  src/layout/header.html
  src/layout/header/header.html
  src/layout/header/header.js
  src/styles/layout/_header.scss
Labels: ✅ Test

#36 🩷 Style : iconfonts 업데이트
  src/assets/banner/banner01.png
  src/assets/banner/banner02.png
  src/assets/banner/banner03.png
  src/assets/banner/banner05.png
  src/assets/fonts/icomoon.eot
  src/assets/fonts/icomoon.svg
  src/assets/fonts/icomoon.ttf
  src/assets/fonts/icomoon.woff
  src/assets/탱탱쫄면.jpg
  src/components/template.html
  src/styles/abstracts/_variables.scss
  src/styles/base/_iconfonts.scss
Labels: 💄 Style

#38 💙 Component : cart page component 생성 및 레이아웃
  src/pages/cart.html
  src/styles/components/_cartList.scss
  src/styles/components/_cartResult.scss
  src/styles/pages/_cart.scss
  src/styles/style.scss
Labels: 💄 Style, 💙 Component

#40 ✅ Test : main 페이지 테스트
  main.js
  package-lock.json
  package.json
  src/assets/banner/banner01.png
  src/assets/visual/visual01.png
  src/assets/visual/visual02.png
  src/assets/visual/visual03.png
  src/assets/visual/visual04.png
  src/pages/main.html
  src/pages/main/main.html
  src/pages/main/swiper.js
  src/styles/pages/_main.scss
  src/styles/pages/_product.scss
Labels: ✅ Test, 🎨 Feat, ⚙️ Ci

#43 ✅ Test : 페이지 전환 테스트 진행 중
  index.html
  main.js
  src/components/template.html
  src/layout/footer/footer.html
  src/layout/header/header.js
  src/pages/cart.html
  src/pages/details.html
  src/pages/login.html
  src/pages/product.html
  src/pages/register.html
  src/styles/pages/_main.scss
Labels: ✅ Test

#46 ♻️ Refactor : 헤더 리팩토링
  src/layout/header/header.html
  src/styles/base/_common.scss
  src/styles/components/_productDetails.scss
  src/styles/layout/_header.scss
  src/styles/pages/_product.scss
Labels: ♻️ Refactor

#50 ♻️ Refactor : 헤더 리팩토링
  src/layout/header/header.html
  src/layout/header/header.js
  src/styles/layout/_header.scss
Labels: ♻️ Refactor

#55 💙 Component : footer webComponent의 하단 이미지 경로 설정, icon 폴더 경로 이동
  public/icons/icon-blog.png
  public/icons/icon-facebook.png
  public/icons/icon-instagram.png
  public/icons/icon-naver-post.png
  public/icons/icon-youtube.png
  src/layout/footer/footer.js
Labels: 💙 Component

#56 💄 Style : scss 및 세미콜론 수정
  index.html
  src/api/pocketbase.js
  src/components/template.html
  src/layout/header/header.html
  src/layout/header/header.js
  src/pages/main/main.html
  src/pages/main/swiper.js
  src/pages/product/product.html
  src/styles/abstracts/_variables.scss
  src/styles/base/_iconfonts.scss
  src/styles/pages/_product.scss
  vite.config.js
Labels: 💄 Style

#61 💄 Style : _main.scss 수정
  src/styles/pages/_main.scss
Labels: 💄 Style

#62 🧡 Markup : cart.html 마크업 및 스타일링
  src/pages/cart/cart.html
  src/styles/components/_cartList.scss
  src/styles/components/_cartResult.scss
  src/styles/pages/_cart.scss
Labels: 💄 Style, 🧡 Markup

#63 Feature/markup/modal/lee
  index.html
  src/assets/images/PopupBanner.png
  src/assets/images/product02.png
  src/assets/images/product03.png
  src/assets/images/product04.png
  src/pages/main/main.html
  src/styles/pages/_main.scss
Labels: 💄 Style, 🧡 Markup

#65 ♻️ Refactor : swiper keyboard 컨트롤
  src/pages/main/swiper.js
Labels: ♻️ Refactor

#66 ♻️ Refactor : 헤더 리팩토링
  src/layout/header/header.js
  src/styles/components/_badge.scss
Labels: ♻️ Refactor

#73 ♻️ Refactor : 헤더/푸터 리팩토링
  public/icons/icon-blog.png
  public/icons/icon-facebook.png
  public/icons/icon-instagram.png
  public/icons/icon-naver-post.png
  public/icons/icon-youtube.png
  public/icons/img_sprite.png
  src/layout/footer/footer.html
  src/layout/footer/footer.js
  src/layout/header/header.html
  src/layout/header/header.js
  src/styles/layout/_footer.scss
  src/styles/layout/_header.scss
Labels: ♻️ Refactor

#76 ♻️ Refactor : 제품 목록, 장바구니 페이지 코드 리팩토링 및 타이틀 위치 통일
  src/pages/cart/cart.html
  src/pages/product/product.html
  src/styles/pages/_cart.scss
  src/styles/pages/_product.scss
Labels: 💄 Style, ♻️ Refactor

#79 💙 Component : 상품 수량 버튼 추가
  src/components/template.html
  src/styles/components/_button.scss
Labels: 💄 Style, 💙 Component

#90 🎨 Feat : 로그인 기능 구현
  main.js
  src/api/defaultAuthData.js
  src/layout/header/header.html
  src/layout/header/header.js
  src/pages/login/login.html
  src/pages/login/login.js
  src/styles/layout/_header.scss
  src/styles/pages/_login.scss
Labels: 🎨 Feat

#96 ♻️ Refactor : 수정된 상품 수량 버튼 페이지에 적용
  index.html
  src/pages/cart/cart.html
  src/pages/main/main.html
  src/pages/productDetail/details.html
  src/styles/components/_cartList.scss
  src/styles/pages/_main.scss
Labels: 💄 Style, 💙 Component

#98 🎨 Feat : 제품 목록 페이지 데이터 렌더링 및 정렬 기능 구현
  src/api/getPbImageURL.js
  src/pages/product/product.html
  src/pages/product/product.js
  src/styles/components/_card.scss
Labels: 🎨 Feat, 💄 Style, 🧡 Markup, 💙 Component

#100 🎨 Feat : cart List의 button toggle, checkbox 전체 선택 구현
  src/pages/cart/cart.html
  src/pages/cart/cart.js
  src/styles/components/_cartList.scss
Labels: 🎨 Feat

#105 🎨 Feat :
  src/pages/cart/cart.html
  src/pages/cart/cart.js
  src/pages/cart/delete.js
Labels: 🎨 Feat

#107 🎨 Feat : 회원가입/탈퇴 기능 구현
  main.js
  src/layout/header/header.js
  src/pages/login/login.js
  src/pages/register/register.html
  src/pages/register/register.js
Labels: 🎨 Feat

#109 💙 Component : cart page 모달창 만들기
  src/components/template.html
  src/styles/components/_address.scss
  src/styles/components/_order.scss
  src/styles/style.scss
Labels: 💄 Style, 💙 Component

#111 ✅ Test : 회원가입, 탈퇴 임시 코드 수정
  src/layout/header/header.js
  src/pages/register/register.html
Labels: ✅ Test

#113 ✅ Test : 회원 탈퇴 코드 수정
  src/layout/header/header.js
  src/pages/login/login.html
  src/pages/register/register.html
Labels: ✅ Test

#115 🎨 Feat : 장바구니 페이지
  src/pages/cart/cart.html
  src/pages/cart/modal.js
  src/styles/components/_address.scss
  src/styles/components/_order.scss
  src/styles/components/_overlay.scss
  src/styles/pages/_cart.scss
  src/styles/style.scss
Labels: 🎨 Feat

#114 🎨 Feat : 필터링 기능 구현 및 아코디언 수정
  src/pages/product/accordion.js
  src/pages/product/product.html
  src/pages/product/product.js
  src/styles/components/_accordion.scss
  src/styles/pages/_product.scss
Labels: 🎨 Feat, 💄 Style

#120 📂 create : lib 폴더 생성
  src/lib/regExp.js
Labels: 📂 create

#122 Refactor/login/an
  main.js
  src/lib/regExp.js
  src/pages/login/login.html
  src/pages/login/login.js
Labels: ✅ Test, ♻️ Refactor

#126 [feature/modify/swiper] - 스와이퍼 기능 구현, 버튼 마크업 수정
  src/pages/main/main.html
  src/pages/main/productCard.js
  src/pages/main/swiper.js
  src/styles/pages/_main.scss
Labels: 🦋 BugFix, 💄 Style, 🧡 Markup

#130 🎨 Feat : 아코디언 가격 필터링, 초기화 기능 구현 및 수정
  src/pages/product/product.html
  src/pages/product/product.js
  src/styles/components/_accordion.scss
Labels: 🎨 Feat

#131 💙 Component : 상품후기, 상품문의 modal 컴포넌트 제작
  src/components/template.html
  src/pages/productDetail/details.html
  src/styles/components/_productInquiryModal.scss
  src/styles/components/_productReviewModal.scss
  src/styles/style.scss
Labels: 💄 Style, 💙 Component

#136 Component : 장바구니 추가 모달 컴포넌트 생성
  src/components/template.html
  src/styles/pages/_main.scss
Labels: 💙 Component

#139 ♻️ Refactor : modal 컴포넌트
  src/components/template.html
  src/styles/components/_modal.scss
  src/styles/style.scss
Labels: 💄 Style, ♻️ Refactor, 💙 Component

#140 🎨 Feat : modal handle 및 함수 생성
  src/components/template.html
  src/lib/timer.js
  src/pages/cart/order.js
  src/pages/productDetail/details.html
  src/pages/productDetail/details.js
  src/pages/productDetail/inquiry.js
  src/pages/productDetail/review.js
  src/styles/components/_modal.scss
  src/styles/components/_productInquiryModal.scss
  src/styles/components/_productReviewModal.scss
  src/styles/pages/_details.scss
Labels: 🎨 Feat

#141 📂 create : accordionToggle.js / count.js 파일 생성
  src/pages/product/accordionToggle.js
  src/pages/product/count.js
  src/pages/product/product.html
  src/pages/product/product.js
Labels: ♻️ Refactor, 📂 create

#146 ♻️ Refactor : cart page 파일 분리
  src/pages/cart/cart.html
  src/pages/cart/cart.js
  src/pages/cart/checkbox.js
  src/pages/cart/order.js
  src/pages/cart/toggle.js
  src/styles/components/_address.scss
  src/styles/pages/_cart.scss
Labels: ♻️ Refactor

#145 create: main폴더 안 main.js 파일 생성 후 모듈 경로 수정
  src/pages/main/main.html
  src/pages/main/main.js
  src/pages/productDetail/details.html
Labels: ♻️ Refactor, 📂 create

#150 ✅ Test : 헤더, 로그인, 회원가입
  src/layout/header/header.js
  src/pages/login/login.html
  src/pages/login/login.js
  src/pages/register/register.html
  src/pages/register/register.js
  src/styles/components/_modal.scss
  src/styles/layout/_header.scss
  src/styles/pages/_register.scss
Labels: ✅ Test

#152 🎨 Feat : checkbox handler
  src/pages/cart/cart.html
  src/pages/cart/cart.js
  src/pages/cart/checkbox.js
  src/pages/cart/index.js
  src/pages/cart/price.js
Labels: 🎨 Feat

#155 Feature/markup/main/lee
  index.html
  main.js
  src/components/template.html
  src/lib/moveTop.js
  src/pages/main/main.html
  src/pages/main/main.js
  src/pages/main/pagination.js
  src/pages/main/productCard.js
  src/pages/main/swiper.js
  src/styles/components/_moveTop.scss
  src/styles/pages/_main.scss
  src/styles/style.scss
Labels: 🎨 Feat, 💄 Style, 💙 Component

#157 ♻️ Refactor : 아이템 리스트의 갯수에 따른 전체갯수 변경
  src/pages/cart/cart.html
  src/pages/cart/cart.js
  src/pages/cart/checkbox.js
  src/pages/cart/delete.js
  src/pages/cart/toggle.js
Labels: ♻️ Refactor

#159 🎨 Feat : 담기 버튼 클릭 시 모달 기능 추가
  src/components/template.html
  src/pages/product/addCart.js
  src/pages/product/product.html
  src/pages/product/product.js
  src/styles/components/_addCartModal.scss
  src/styles/components/_bubble.scss
  src/styles/style.scss
Labels: 🎨 Feat, 💄 Style, 💙 Component, 📂 create

#162 ✅ Test : 메인 페이지 상품 링크 디테일 페이지로 수정
  src/pages/main/getPbData.js
  src/pages/main/productCard.js
Labels: ✅ Test, ♻️ Refactor

#164 ♻️ Refactor : 회원가입 리팩토링
  src/lib/regExp.js
  src/pages/register/register.html
  src/pages/register/register.js
Labels: 🎨 Feat, ♻️ Refactor

#170 ♻️ Refactor : details 페이지 보강
  src/lib/priceHandler.js
  src/pages/productDetail/details.js
  src/pages/productDetail/productRender.js
Labels: 🎨 Feat, ♻️ Refactor

#173 ♻️ Refactor : product.js 코드 리팩토링
  src/pages/product/createProductCard.js
  src/pages/product/filter.js
  src/pages/product/product.js
  src/pages/product/sort.js
Labels: ♻️ Refactor, 📂 create

#174 ♻️ Refactor : 제품 갯수에 따른 최종 가격 변경
  src/lib/priceHandler.js
Labels: 🎨 Feat, ♻️ Refactor

#177 💙 Component : productCard 컴포넌트 수정
  src/pages/product/createProductCard.js
Labels: 💙 Component

#181 🦋 BugFix : addcart 모달 수량 카운트 부분 수정
  src/pages/product/addCart.js
Labels: 🦋 BugFix

#183 ♻️ Refactor : details page 수정
  src/pages/productDetail/details.html
  src/pages/productDetail/details.js
  src/pages/productDetail/productRender.js
  src/pages/productDetail/productTab.js
  src/styles/pages/_details.scss
Labels: 🎨 Feat, ♻️ Refactor

#186 💚 Docs : README.md 내용 추가
  README.md
Labels: 💚 Docs

#188 💄 Style : bubble.scss / product.scss 수정
  src/pages/product/addCart.js
  src/pages/product/bubble.js
  src/pages/product/product.html
  src/styles/components/_bubble.scss
  src/styles/pages/_product.scss
Labels: 🦋 BugFix, 💄 Style

#189 ♻️ Refactor : component 수정
  src/components/template.html
  src/styles/components/_address.scss
  src/styles/components/_modal.scss
Labels: 💄 Style, ♻️ Refactor

#192 Style/header/an
  package-lock.json
  package.json
  src/layout/header/header.js
  src/pages/register/register.js
  src/styles/layout/_header.scss
Labels: ⚙️ Ci, 💄 Style, ♻️ Refactor

#194 🧡 Markup : main.html 문서 수정
  index.html
  main.js
  src/pages/main/close.js
  src/pages/main/details.js
  src/pages/main/getPbData.js
  src/pages/main/main.html
  src/pages/main/main.js
  src/pages/main/pagination.js
  src/pages/main/productCard.js
  src/pages/main/productCards.js
  src/pages/main/swiper.js
  src/styles/pages/_main.scss
Labels: 🧡 Markup

#196 ✅ Test : 장바구니 버블 데이터 렌더링 테스트
  src/layout/header/header.js
  src/pages/product/addCart.js
  src/pages/product/bubble.js
  src/pages/product/product.html
  src/styles/layout/_header.scss
  src/styles/pages/_product.scss
Labels: ✅ Test, 💄 Style, 🧡 Markup, 🔥 Remove

#199 💄 Style : 페이지별 스타일 수정
  src/components/template.html
  src/pages/product/product.html
  src/styles/components/_accordion.scss
  src/styles/components/_button.scss
  src/styles/components/_card.scss
  src/styles/components/_cartList.scss
  src/styles/components/_productTab.scss
  src/styles/components/_textInput.scss
  src/styles/layout/_header.scss
  src/styles/pages/_details.scss
  src/styles/pages/_main.scss
Labels: 💄 Style

#205 ✅ Test : 최근 본 상품 스와이퍼 테스트
  index.html
  src/pages/main/swiper.js
  src/styles/pages/_main.scss
Labels: ✅ Test

#206 🎨 Feat : cartpage 장바구니 담기 구현
  src/pages/cart/addCartEvent.js
  src/pages/cart/cart.html
  src/pages/cart/cart.js
  src/pages/cart/checkbox.js
  src/pages/cart/delete.js
  src/pages/cart/order.js
  src/pages/cart/price.js
  src/pages/cart/toggle.js
Labels: 🎨 Feat

#208 ♻️ Refactor : cart page 리팩토링
  src/pages/cart/addCartEvent.js
  src/pages/cart/cart.html
  src/pages/cart/checkbox.js
  src/pages/cart/delete.js
  src/pages/cart/order.js
  src/pages/cart/toggle.js
  src/pages/main/productSwiperRender.js
  src/pages/main/sidebarData.js
  src/styles/components/_cartList.scss
  src/styles/components/_productInquiryModal.scss
  src/styles/components/_productReviewModal.scss
Labels: ♻️ Refactor

#215 💚 Docs : Update README.md
  README.md
Labels: 💚 Docs
